language: node_js
os:
  - linux
  - osx
  - windows
node_js:
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"
notifications:
  slack: victorsapps:80rlc7qpeKiPjgEHgi1cMmp5
before_install:
    - npm i -g mocha
    - npm i -g eslint